### ISSUE TITLE
Data Installer improvements

### ISSUE THREAD

**Issue by Tom-III** [q-gears/q-gears#127]
The field decompiler does a great job at decompiling the fields and converting them to LUA however there are small bugs with variables and stuff that make certain fields buggy.
These must be fixed in order to have playable fields.

Running the bombing missions from the data installer
![Color distrtion](http://i.imgur.com/xKtfTrt.png)

**Comment by paulsapps** [comment]
I'll close this, I've raised 3 specific issues to deal with what is required to make this work properly.
