### ISSUE TITLE
Menu dialogs look bad

### ISSUE THREAD

**Issue by Tom-III** [q-gears/q-gears#40]
The borders around the dialogs look very bad, they are not smooth and sometimes glitch a pixel or two up or down and don't connect properly.  This is shown in the image below:

![alt text](http://i.imgur.com/qXo1AHc.png "Pixel Issue")

**Comment by CapsAdmin** [comment]
It looks like it has something to do with pixel positions not being rounded somewhere. I had a quick look and tried to round some things. In some cases it would maybe improve a bit but it was still wrong.

**Comment by Tom-III** [comment]
I think that if we use the PC versions font and dialogue boxes it will look a lot better since its hq2x on the font (upscaled)

**Comment by ytn3rd** [comment]
Yeah I have seen similar aliasing issues when working on iOS apps when I
set the position of a views position to not rounded float positions.


Brad Moore// Co-Founder & CTO[image: Four Pi] <http://4pi.com.au/>+61 434
260 154// AU

**Comment by myst6re** [comment]
Using textures from PC version should be an option, not a solution.

**Comment by paulsapps** [comment]
Agree

**Comment by Tom-III** [comment]
I don't think the borders were antialiased in the original game, I could be wrong tho

**Comment by paulsapps** [comment]
I think Akari said this aligment issue is fixed in his changes. Maybe download his binaries and check?

**Comment by Akari1982** [comment]
this thing was resolved.

**Comment by paulsapps** [comment]
:+1:  closing
