### ISSUE TITLE
Update unit tests

### ISSUE THREAD

**Issue by paulsapps** [q-gears/q-gears#47]
Unit tests need to run as part of the travis build - however they require test files. We need a test on non copyrighted tests files. Additionally these files should be converted to a byte array in a .h file so that the unit test isn't doing disk I/O.

Coveralls can also be enabled once this is done.

**Comment by zerotacg** [comment]
do you mind I/O for any special reason? the LGP Archive [1][2] is meant to read a file

[1] https://github.com/q-gears/q-gears/blob/master/QGearsMain/src/data/QGearsLGPArchive.cpp
[2] https://github.com/q-gears/q-gears/blob/master/Tests/QGearsMain/src/test_QGearsLGPArchive.cpp

**Comment by paulsapps** [comment]
Just because when there are many (when we get > 100) tests all the small I/O amounts really beef up the test execution time. It also makes it impossible to fail. 

Might have to refactor slightly to allow passing in a buffer?

I.e 

  std::ifstream *ifs( OGRE_NEW_T( std::ifstream, Ogre::MEMCATEGORY_GENERAL )( mName.c_str(), std::ifstream::binary ) );

Could use a std::stringstream that copies in the buffer - should have the same interface etc.

**Comment by zerotacg** [comment]
only partly fixed, close was not intended

**Comment by paulsapps** [comment]
Should probably test exporting too if it isn't already, a test case for #57 would be nice too

**Comment by paulsapps** [comment]
Test now run on Linux and OSX and Coveralls is enabled, 12% coverage is current stats.
